In [7]:
import pandas as pd
import numpy as np
import plotly.express as px
import seaborn as sns
import matplotlib.pyplot as plt

In [8]:
import warnings
warnings.filterwarnings('ignore')

In [9]:
df=pd.read_csv(r"E:\datasets\black friday sales prediction\BlackFridaySales.csv")

In [10]:
df=df[df['Product_Category_2'].isnull()==False]

In [11]:
df=df[df['Product_Category_3'].isnull()==False]


In [52]:
df.head()

User_ID Product_ID Gender    Age  Occupation City_Category  \
1   1000001  P00248942      F   0-17          10             A   
6   1000004  P00184942      M  46-50           7             B   
13  1000005  P00145042      M  26-35          20             A   
14  1000006  P00231342      F  51-55           9             A   
16  1000006   P0096642      F  51-55           9             A   

   Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
1                           2               0                   1   
6                           2               1                   1   
13                          1               1                   1   
14                          1               0                   5   
16                          1               0                   2   

    Product_Category_2  Product_Category_3  Purchase  
1                  6.0                14.0     15200  
6                  8.0                17.0     19215  
13                 2.0                 5.0     15665  
14                 8.0                14.0      5378  
16                 3.0                 4.0     13055

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 166821 entries, 1 to 545914
Data columns (total 12 columns):
 #   Column                      Non-Null Count   Dtype  
---  ------                      --------------   -----  
 0   User_ID                     166821 non-null  int64  
 1   Product_ID                  166821 non-null  object 
 2   Gender                      166821 non-null  object 
 3   Age                         166821 non-null  object 
 4   Occupation                  166821 non-null  int64  
 5   City_Category               166821 non-null  object 
 6   Stay_In_Current_City_Years  166821 non-null  object 
 7   Marital_Status              166821 non-null  int64  
 8   Product_Category_1          166821 non-null  int64  
 9   Product_Category_2          166821 non-null  float64
 10  Product_Category_3          166821 non-null  float64
 11  Purchase                    166821 non-null  int64  
dtypes: float64(2), int64(5), object(5)
memory usage: 16.5+ MB


In [13]:
df.corr()

User_ID  Occupation  Marital_Status  Product_Category_1  \
User_ID             1.000000   -0.014519        0.018639            0.010370   
Occupation         -0.014519    1.000000        0.027368           -0.013682   
Marital_Status      0.018639    0.027368        1.000000            0.015682   
Product_Category_1  0.010370   -0.013682        0.015682            1.000000   
Product_Category_2  0.009095    0.001336        0.014813            0.499115   
Product_Category_3  0.003419    0.013263        0.019473            0.229678   
Purchase           -0.000590    0.025048        0.004603           -0.396558   

                    Product_Category_2  Product_Category_3  Purchase  
User_ID                       0.009095            0.003419 -0.000590  
Occupation                    0.001336            0.013263  0.025048  
Marital_Status                0.014813            0.019473  0.004603  
Product_Category_1            0.499115            0.229678 -0.396558  
Product_Category_2            1.000000            0.543649 -0.153711  
Product_Category_3            0.543649            1.000000 -0.022006  
Purchase                     -0.153711           -0.022006  1.000000

Splitting the data into test and train

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X = df.iloc[:, 8:11].values
X

array([[ 1.,  6., 14.],
       [ 1.,  8., 17.],
       [ 1.,  2.,  5.],
       ...,
       [ 2.,  3., 10.],
       [ 1.,  2., 15.],
       [ 1.,  2., 11.]])

In [16]:
y=df.iloc[:,11]
y

1         15200
6         19215
13        15665
14         5378
16        13055
          ...  
545902     8047
545904    16493
545907     3425
545908    15694
545914    11640
Name: Purchase, Length: 166821, dtype: int64

In [17]:
X_train, X_test,y_train, y_test = train_test_split(X, y, test_size=0.2)

In [18]:
X_train

array([[ 2.,  4.,  5.],
       [ 1.,  8., 17.],
       [ 1.,  6., 15.],
       ...,
       [ 1.,  6., 14.],
       [ 8., 14., 17.],
       [ 1., 14., 16.]])

scaling

In [19]:
y_train

172973    16337
304504    15787
347872     8181
78510      5396
265380    12066
          ...  
360215     8117
359201     6914
419089    15733
343878     9971
246583    15249
Name: Purchase, Length: 133456, dtype: int64

In [20]:
from sklearn.preprocessing import MinMaxScaler


In [21]:
scaler = MinMaxScaler()
scaler.fit(X_train)

MinMaxScaler()

In [22]:
X_train = scaler.transform(X_train)
X_train.shape

(133456, 3)

In [23]:
X_test=scaler.transform(X_test)

In [24]:
y_train=np.array(y_train).reshape(len(y_train),1)
sc = MinMaxScaler()
sc.fit(y_train)
y_train=sc.transform(y_train)

In [25]:
y_test=np.array(y_test).reshape(len(y_test),1)
y_test=sc.transform(y_test)

RANDOM FOREST

In [26]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor()

In [27]:
regressor.fit(X_train, y_train)

RandomForestRegressor()

In [28]:
y_pred = regressor.predict(X_test)
y_pred

array([0.56874722, 0.62183594, 0.54356831, ..., 0.1026788 , 0.44014489,
       0.49961773])

In [29]:
from sklearn.metrics import r2_score,mean_squared_error

mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

Mean Squared Error: 0.0221844316733614


In [30]:
r2_score(y_test,regressor.predict(X_test))

0.5173007623470631

grid serach

In [31]:
from sklearn.model_selection import GridSearchCV

In [32]:
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 5, 10]
}

In [33]:
grid_search = GridSearchCV(regressor, param_grid, cv=5)

In [34]:
grid_search.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=RandomForestRegressor(),
             param_grid={'max_depth': [None, 5, 10],
                         'n_estimators': [50, 100, 200]})

In [35]:
best_model = grid_search.best_estimator_
y_pred = best_model.predict(X_test)

In [36]:
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)


Mean Squared Error: 0.022182251497932952


In [37]:
r2=r2_score(y_test,y_pred)
print("r2_square ",r2)

r2_square  0.517348199623472


Decision tree

In [38]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import accuracy_score


In [39]:
clf = DecisionTreeRegressor()

In [40]:
clf.fit(X_train, y_train)

DecisionTreeRegressor()

In [41]:
y_pred = clf.predict(X_test)

In [42]:
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

Mean Squared Error: 0.022182440784208047


In [43]:
r2=r2_score(y_test,y_pred)
print("r2_square ",r2)

r2_square  0.5173440810441894


multi linear regression

In [44]:
from sklearn.linear_model import LinearRegression

In [45]:
reg = LinearRegression()
reg.fit(X_train, y_train)

LinearRegression()

In [46]:
y_pred = regressor.predict(X_test)

In [47]:
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

Mean Squared Error: 0.0221844316733614


In [48]:
r2=r2_score(y_test,y_pred)
print("r2_square ",r2)

r2_square  0.5173007623470631


In [49]:
import pickle

In [51]:
fn="black-friday.sav"
pickle.dump(regressor,open(fn,'wb'))